export const LOADED_PERSONS_SMALL = 'LOADED_PERSONS_SMALL';
export const START_TABLE = 'START_TABLE';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SORT = 'SORT';
export const OPEN_PERSON = 'OPEN_PERSON';
export const ADD_PERSON = 'ADD_PERSON';
export const SEARCH = 'SEARCH';

export const TOGGEL_FORM = 'TOGGEL_FORM';
export const CHANGE_VALUE_ID = 'CHANGE_VALUE_ID';
export const CHANGE_VALUE_FIRSTNAME = 'CHANGE_VALUE_FIRSTNAME';
export const CHANGE_VALUE_LASTNAME = 'CHANGE_VALUE_LASTNAME';
export const CHANGE_VALUE_EMAIL = 'CHANGE_VALUE_EMAIL';
export const CHANGE_VALUE_PHONE = 'CHANGE_VALUE_PHONE';
export const RESET_FORM = 'RESET_FORM';

